### ISSUE TITLE
macOS Dependencies

### ISSUE THREAD

**Issue by yashomer1994** [quark-engine/quark-engine#83] opened 2020-11-02 12:49 UTC
Dependencies error during the installation of the quark-engine on macOS Catalina - 10.15.7.

Error  : -
pkg_resources.DistributionNotFound: The 'androguard==3.4.0a1' distribution was not found and is required by quark-engine

<img width="1016" alt="Screenshot 2020-11-02 at 6 18 56 PM" src="https://user-images.githubusercontent.com/18115054/97869748-fbcf3680-1d37-11eb-82e5-9132b3d03782.png">

**Comment by krnick** [comment] 2020-11-03 09:03
Hello @yashomer1994, thank you for reporting the issue, it could be run on macOS Mojave 10.14.6 by me, also in ubuntu latest version, maybe you can try to use Docker or other virtual environments to develop instead of installing it directly in your computer environment.

**Comment by yashomer1994** [comment] 2020-11-03 09:09
Hi , 
Yes it’s working in linux and docker. 
But i have tested on MacOS Catalina 10.15.7   
I have also shared the screenshot of error in Issue section

**Comment by krnick** [comment] 2020-11-03 09:12
Hello @yashomer1994 , I saw your python version is 2.7, but quark-engine required the python version is >= 3.7.

**Comment by yashomer1994** [comment] 2020-11-03 09:22
Hi , 
I also have python 3.9 i will check again and let you know 

Thanks.

**Comment by yashomer1994** [comment] 2020-11-03 10:16
Python 3.9 not supported.
Installation successful over python3 o macOS 10.15.7.
Running quark-engine using python3 broke the engine due to dependency issues .
Please find the attached screenshot.

<img width="1039" alt="Screenshot 2020-11-03 at 3 28 44 PM" src="https://user-images.githubusercontent.com/18115054/97973131-a05e8080-1deb-11eb-97af-fa5633d86f45.png">
``

**Comment by sidra-asa** [comment] 2020-11-04 09:41
@yashomer1994  I tested in python 3.9.0 environments in Mac OS. 
It looks that both using pip package installer and following the installation instruction in README are all fine.

``` BASH
pip package installer
# pip install quark-engine

installation instruction
$ git clone https://github.com/quark-engine/quark-engine.git; cd quark-engine/quark
$ pipenv install --skip-lock
$ pipenv shell
```

<img width="1273" alt="Screen Shot 2020-11-04 at 17 24 35" src="https://user-images.githubusercontent.com/7848936/98094660-8a70be80-1ec4-11eb-941d-4973b6d6a3a2.png">

Can you provide more information about how you install quark-engine ?

**Comment by yashomer1994** [comment] 2020-11-04 11:17
Hi , I have followed the README and tested out , But after using command pip install quark-engine and then follow other instructions , I am getting error please find the attached screen shot.
I am using zsh shell.

<img width="1026" alt="Screenshot 2020-11-04 at 4 43 48 PM" src="https://user-images.githubusercontent.com/18115054/98104772-edf6ee00-1ebc-11eb-9b44-33e9d5433a59.png">

**Comment by 18z** [comment] 2020-11-05 01:48
@yashomer1994 

Can you help us to make sure that this dependency error occurs not just in your environment?
We need to first be sure that this error is reproducible in the other peoples' computer which have the same environment like yours. 

So I think the first step we can do is to know your environment setups.
For example: 

OS: macOS Catalina version 10.15.7
Python Version: 3.9
Python Package Manager: pipenv version 2020.11.4

or anything else you think is helpful for the trouble shooting. 😄

**Comment by sidra-asa** [comment] 2020-11-05 03:30
@yashomer1994 

Please try the following instruction:

``` Bash

$ cd quark-engine/quark
$ pipenv --rm
$ pipenv --python /usr/local/Cellar/python\@3.9/3.9.0_1/bin/python3.9
$ pipenv install --skip-lock
$ pipenv shell
(quark-engine) $ quark -h

```

You may see some warning about using 3.9.0, but it's fine.
Be sure all the dependencies are installed like following screenshot:

<img width="446" alt="Screen Shot 2020-11-05 at 11 22 52" src="https://user-images.githubusercontent.com/7848936/98194075-893da100-1f59-11eb-99c2-f72af6ddcba7.png">

If any problem, please let us know.  :P

**Comment by yashomer1994** [comment] 2020-11-05 05:00
Please find the below screenshot I have already tested these work arounds . 
macOS 10.15.7
python- 3.9
<img width="1440" alt="Screenshot 2020-11-05 at 10 28 21 AM" src="https://user-images.githubusercontent.com/18115054/98199697-ce5dd500-1f51-11eb-9dec-278d0001ca06.png">

**Comment by yashomer1994** [comment] 2020-11-05 05:07
> @yashomer1994
> 
> Can you help us to make sure that this dependency error occurs not just in your environment?
> We need to first be sure that this error is reproducible in the other peoples' computer which have the same environment like yours.
> 
> So I think the first step we can do is to know your environment setups.
> For example:
> 
> OS: macOS Catalina version 10.15.7
> Python Version: 3.9
> Python Package Manager: pipenv version 2020.11.4
> or anything else you think is helpful for the trouble shooting. 😄


- Yes the same I am using with  pipenv, version 2020.8.13 , which also tried to update but this is latest one.
- To help People, we can make requirements.txt file in which these dependencies can be installed before installing engine to avoid dependencies issues. That's why I have created PR for the same.

**Comment by sidra-asa** [comment] 2020-11-05 06:03
@yashomer1994 

According to your screenshot, I guess you have installed engine via pip.
There may be some package import issue.
To make it clear, please uninstall engine via pip, then try it in pipenv shell.

```Bash

# At first, be sure you are NOT int pipenv shell.
$ cd quark-engine/
$ pip uninstall quark-engine
$ pipenv shell
(quark-engine) $ quark -h

```

Please let us know if it works or not.

**Comment by yashomer1994** [comment] 2020-11-05 06:15
> @yashomer1994
> 
> According to your screenshot, I guess you have installed engine via pip.
> There may be some package import issue.
> To make it clear, please uninstall engine via pip, then try it in pipenv shell.
> 
> ```shell
> # At first, be sure you are NOT int pipenv shell.
> $ cd quark-engine/
> $ pip uninstall quark-engine
> $ pipenv shell
> (quark-engine) $ quark -h
> ```
> 
> Please let us know if it works or not.


I have tried different ways, normal as per instructions given, then told me install using pip then I have tried that one, that the instructions given by you, and several others.

But I will show once again.


<img width="1031" alt="Screenshot 2020-11-05 at 11 44 58 AM" src="https://user-images.githubusercontent.com/18115054/98204602-5ba62700-1f5c-11eb-89ab-b77fa42a7eb1.png">

**Comment by sidra-asa** [comment] 2020-11-05 06:54
@yashomer1994 

Sorry for the annoying instructions so far. I just want to figure out the root cause.
Please try it one more for us with following instruction:

```Bash

$ ~/.local/share/virtualenvs/quark-engine-k28vpGZb/bin/quark -h

```

If it works, it may be the issue with pipenv and zsh.
It seems some solutions are available:
https://github.com/pypa/pipenv/issues/1058

If any problem, please let us know.

**Comment by yashomer1994** [comment] 2020-11-05 07:49
> @yashomer1994
> 
> Sorry for the annoying instructions so far. I just want to figure out the root cause.
> Please try it one more for us with following instruction:
> 
> ```shell
> $ ~/.local/share/virtualenvs/quark-engine-k28vpGZb/bin/quark -h
> ```
> 
> If it works, it may be the issue with pipenv and zsh.
> It seems some solutions are available:
> [pypa/pipenv#1058](https://github.com/pypa/pipenv/issues/1058)
> 
> If any problem, please let us know.


May be the issue is zsh and pipenv because the same was running on Linux and docker without any issues.

**Comment by sidra-asa** [comment] 2022-09-29 10:25
On macOS 11.6.8 (Big Sur) with python 3.8, 3.9, building and analysis are all fine.
Also, basic testing on macOS environment is included in the [smoke test](https://github.com/quark-engine/quark-engine/blob/master/.github/workflows/smoke_test.yml), so we close this issue.
Nevertheless, any relevant issue is free to create.

**Closed** 2022-09-29 10:25 UTC
Labels: test-required, issue-processing-state-01
